version: '3.8'

services:
  akaunting:
    image: akaunting/akaunting:latest
    container_name: akaunting
    ports:
      - "8000:80"
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: akaunting
      MYSQL_USER: akaunting
      MYSQL_PASSWORD: akaunting_password
    networks:
      - app-network

  nessus:
    image: tenableofficial/nessus
    container_name: nessus
    ports:
      - "8834:8834"
    environment:
      ACCEPT_EULA: "yes"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
