name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Start Containers
        run: |
          docker-compose up -d
          docker ps

  nessus-scan:
    runs-on: ubuntu-22.04
    needs: build-and-deploy

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Nessus Container IP
        run: ./get_nessus_ip.sh

      - name: Run Nessus Scan
        run: ./nessus-scan.sh

      - name: Upload Nessus Report
        uses: actions/upload-artifact@v3
        with:
          name: nessus-report
          path: ./reports/nessus_report.json
