name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

      - name: Build and Start Containers
        run: |
          docker-compose up -d
          docker ps

  nessus-scan:
    runs-on: ubuntu-22.04
    needs: build-and-deploy

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Nessus Container IP
        run: ./nessus/get_nessus_ip.sh

      - name: Run Nessus Scan
        run: ./nessus/nessus-scan.sh

      - name: Upload Nessus Report
        uses: actions/upload-artifact@v3
        with:
          name: nessus-report
          path: ./reports/nessus_report.json
